name: argos-translate
base: core18 
version: '1.0' 
summary: Argos Translate
description: |
  Offline translation app
icon: snap/gui/icon.png

grade: stable
confinement: strict

apps:
  argos-translate: 
    adapter: full
    command: desktop-launch $SNAP/bin/argos-translate
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
       
# From snapcraft-desktop-helpers
# https://github.com/ubuntu/snapcraft-desktop-helpers
parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  argos-translate:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: .
    # Based on ericoporto/pyqthelloworld
    # https://github.com/ericoporto/pyqthelloworld
    build-packages:
      - python3
      - python3-pyqt5
      - execstack
    stage-packages:
      - python3
      - python3-pyqt5
      - libc-bin
      - locales

  model-files:
    source: packages
    plugin: dump
    organize:
      '*' : packages/

