name: argos-translate
base: core18 
version: '1.0' 
summary: Argos Translate
description: |
  Offline translation app
icon: snap/gui/icon.png

grade: stable
confinement: strict

apps:
  argos-translate: 
    adapter: full
    command: bin/argos-translate
    extensions: [gnome-3-28]
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - unity7
      - wayland
      - x11

parts:
  argos-translate:
    plugin: python
    python-version: python3
    source: .

  model-files:
    source: packages
    plugin: dump
    organize:
      '*' : packages/

